rendezvous_server = '43.142.49.118:21116'
nat_type = 1
serial = 0

[options]
relay-server = '43.142.49.118:21117'
key = 'CulxL9oAzCZJT+oJdFQijgj+jti4Z0qJeBnvVFBwvjg='
custom-rendezvous-server = '43.142.49.118:21116'
local-ip-addr = '10.0.0.7'
