id = ''
enc_id = '00ZnQbmAph8eaaIWmVWaZuMc4iZlEfboCdIA=='
password = '00WWLv4Zs4DvSKxqUcOcrolIduNxFMMw=='
salt = 'dem6cm'
key_pair = [
    [
    202,
    210,
    47,
    92,
    72,
    26,
    213,
    122,
    55,
    143,
    92,
    237,
    141,
    125,
    137,
    20,
    35,
    11,
    57,
    241,
    218,
    173,
    74,
    2,
    109,
    2,
    4,
    237,
    86,
    40,
    129,
    183,
    107,
    240,
    199,
    75,
    38,
    157,
    147,
    184,
    63,
    236,
    239,
    149,
    243,
    225,
    228,
    255,
    202,
    73,
    16,
    200,
    6,
    144,
    34,
    23,
    114,
    194,
    126,
    17,
    91,
    140,
    137,
    32,
],
    [
    107,
    240,
    199,
    75,
    38,
    157,
    147,
    184,
    63,
    236,
    239,
    149,
    243,
    225,
    228,
    255,
    202,
    73,
    16,
    200,
    6,
    144,
    34,
    23,
    114,
    194,
    126,
    17,
    91,
    140,
    137,
    32,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
"43.142.49.118:21116" = true
rs-cn = true
rs-sg = true
www = true
